### ISSUE TITLE
regexps not working

### ISSUE THREAD

**Issue by QianChenglong** [bensadeh/tailspin#175]
~/.config/tailspin/theme.toml

```toml
[[regexps]]
regex = '(m)'
style = { fg = "red" }
[[regexps]]
regex = 'Listening .*'
style = { fg = "blue" }
```
<img width="1810" alt="image" src="https://github.com/user-attachments/assets/886c5839-2757-4fe3-9ea8-23938cf90bbb">
