### ISSUE TITLE
Builtin patterns have precedence over custom patterns

### ISSUE THREAD

**Issue by shrx** [bensadeh/tailspin#214]
Builtin regex patterns have precedence over custom patterns defined in `theme.toml`.

Custom pattern:

```toml
[[regexes]]
regex = '\d(?:[-.]?\d)*\.\d(?:[-.]?\d)*\.\d(?:[-.]?\d)*\.\d(?:[-.]?\d+)'
style = { fg = "red" }
```

Expected behavior: ![Image](https://github.com/user-attachments/assets/dff617bb-8258-490d-b432-7d2cc2f7f8ad)

Actual behavior: The substring is matched as a combination of IP addresses and float numbers ![Image](https://github.com/user-attachments/assets/2ca36315-4e7e-4086-ad88-485e078dedd3)
