### ISSUE TITLE
Unable to disable `Date` group in log output?

### ISSUE THREAD

**Issue by peterkos** [bensadeh/tailspin#44]
Hi!

I'm struggling to disable the highlight group for `Date`, i.e., hide the `Date` column in log output

From README:
```md
To disable a highlight group, either comment it out or delete it.
```

I've attempted:
```toml
# 1) comment out
#[groups.date]

# 2) set disabled = true
[groups.date]
disabled = true
```

It looks like I can set disabled on `Date` and it should work? I may be missing something obvious here 😅 
https://github.com/bensadeh/tailspin/blob/504e47fbc7a325f3ebacb10346a449bba2a64f26/src/theme/mod.rs#L62-L68

**Comment by peterkos** [comment]
Ah, on second thought: I think I'm mixing up "disable highlight group" with "hide a group in output" 👀 which is my end goal

**Comment by bensadeh** [comment]
Hello there!

Ah, I see, that's an interesting feature request! I guess it is somewhat related to #9? That issue has been put on hold because it is somewhat complex (like you mentioned).

However, adding a way to omit / hide the date might be a simpler stop-gap solution until something better is in place for the dates.

**Comment by peterkos** [comment]
Yeah; I'm playing around with this locally, will post updates when something ✨ tangible has appeared

**Comment by bensadeh** [comment]
Hi again @peterkos ,

I've merged the changes into main from #50. 

The changes allows you to shorten the date and time segments into another string (which can be empty) like so:

```toml
[date]
shorten = { to = "␣", style = { fg = "magenta" } }

[time]
shorten = { to = "␣", style = { fg = "blue" } }
```

Let me know if this is a good solution for you.
